<?php
$_lang['modxcomments']='Comments';
$_lang['modxcomments.resource']='Resource';
$_lang['modxcomments.author']='Author';
$_lang['modxcomments.email']='Email';
$_lang['modxcomments.comment']='Comment';
$_lang['modxcomments.status']='Status';
$_lang['modxcomments.createdon']='Created';
$_lang['modxcomments.search']='Search comments…';
$_lang['modxcomments.all']='All';
$_lang['modxcomments.published']='Published';
$_lang['modxcomments.pending']='Pending';
$_lang['modxcomments.spam']='Spam';
$_lang['modxcomments.publish']='Publish';
$_lang['modxcomments.mark_pending']='Mark pending';
$_lang['modxcomments.mark_spam']='Mark spam';
$_lang['modxcomments.delete']='Delete';
$_lang['modxcomments.delete_confirm']='Soft-delete this comment? Replies will remain.';
$_lang['modxcomments.actions']='Actions';
