<?php
$_lang['modxcomments']='Комментарии';
$_lang['modxcomments.resource']='Ресурс';
$_lang['modxcomments.author']='Автор';
$_lang['modxcomments.email']='Email';
$_lang['modxcomments.comment']='Комментарий';
$_lang['modxcomments.status']='Статус';
$_lang['modxcomments.createdon']='Создан';
$_lang['modxcomments.search']='Поиск комментариев…';
$_lang['modxcomments.all']='Все';
$_lang['modxcomments.published']='Опубликованные';
$_lang['modxcomments.pending']='На модерации';
$_lang['modxcomments.spam']='Спам';
$_lang['modxcomments.publish']='Опубликовать';
$_lang['modxcomments.mark_pending']='Отправить на модерацию';
$_lang['modxcomments.mark_spam']='Пометить как спам';
$_lang['modxcomments.delete']='Удалить';
$_lang['modxcomments.delete_confirm']='Удалить комментарий? Ответы в ветке сохранятся.';
$_lang['modxcomments.actions']='Действия';
